### ISSUE TITLE
请求添加对Bangumi token的支持和排序功能

### ISSUE THREAD

**Issue by Patrick-Ze** [kjtsune/UserScripts#2]
大佬能否考虑下支持bgm的token和排序功能？ 用户[申请bgm token](https://next.bgm.tv/demo/access-token)后，可以获取到NSFW类的番剧的信息；排序功能就是按照Bangumi的评分进行排序，方便选番。

在GPT的帮助下写了渣渣代码 (PR #1 )，没有美感所以就关掉了，只是作为期望的功能的参考

**Comment by kjtsune** [comment]
能跑就行了，问题不大，我也是菜鸟。就是这个变量命名统一驼峰好点，还有做个标记或者判断，避免一直重复计算。

**Comment by Patrick-Ze** [comment]
我发现脚本会一直运行（`logger.info(animeList)`会一直输出），有想过加停止功能，但是不知道怎么让异步函数停止

https://github.com/kjtsune/UserScripts/blob/557ff827e8237d4b29606eb16db9389ab0bf621a/mikananiBgmScore/mikananiBgmScore.js#L372

**Comment by kjtsune** [comment]
打印的这个像你改debug就可以了。
排序的，你可以在循环到最后一天的时候，往最后一天的元素塞个字段进去。然后在循环开始的时候检查最后一天的这个字段是否存在。这样子就差不多了。
打印的这个其实也可以根据这个判断，不过看起来没什么资源消耗，我就没管他了。

**Comment by kjtsune** [comment]
https://github.com/kjtsune/UserScripts/commit/c410b80d1d3fdbfe98e34de4b9990228f7c6831d
